language: ruby
rvm:
- 2.2.0
sudo: false
cache: bundler
git:
  submodules: false
script: "./go ci_build"
notifications:
  email:
    recipients:
    - hillary.hartley@gsa.gov
    - gregory.boone@gsa.gov
    on_success: change
    on_failure: change
branches:
  only:
  - staging
  - production
deploy:
  provider: cloudfoundry
  api: https://api.18f.gov
  username: 18F-deployer
  password:
    secure: EyrUjA/+xsN1UsgppsHqoJe6W4c49305XMuuWu0bE2N5Ixh56EbH9I0XaHBam98jlNa83WeiBw4yFuREC8MUE6aQzLYG0gDfRnwA4Uc4gbIciwea3IRB0stFPNwetX2OU65TK74L4ZiGvTwcrlzjLXV3j4ieEyGezN7sEnk23ks=
  organization: 18F
  space: site
  on:
    repo: 18F/18f.gsa.gov
    branch: staging
